<a href="https://colab.research.google.com/github/preeti13456/pytorch/blob/master/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Here we are using pytorch library with torch.tensor() functionalities such that it will help to take all the inputs vectors, matrices, 3d-arrays, numpy arrays. And help to apply mathematics on it and convert it in tensor form .

### Functions we can incorporate in torch.tensor() matrix.

An short introduction about PyTorch and about the chosen functions. 
- function 1 : math functions like torch.rand(), torch.abs_() and torch.allclose
- function 2 : torch.as_strided (layout functions)
- function 3 : In these the functions deals with the individual elements instead of clusters.
- function 4 : It deals with subtensors such as storage_offset() function.
- function 5 : symeifg(eigenvalue functions)

In [0]:
# Import torch and other required modules
import torch
import os
import numpy as np

## Function 1 - Some of the math functions we used here to play with the tensor inputs.

# 1. tensor = torch.rand ((no.of rows, no. of columns)),
# 2. torch.abs_(input, alpha=1)
# 3.  torch.allclose(input, other, rtol=1e-05, atol=1e-08, equal_nan=False)

In [0]:
# Example 1 - working (change this)

#x = np.array([[1, 2], [3, 4.]])
#y = torch.from_numpy(x)
tensor=torch.rand((2,3))
z = tensor.new_tensor([[9,0,-7.],[5,7,.0]], requires_grad=False)
z.shape
z.permute([-2,1])


tensor([[ 9.,  0., -7.],
        [ 5.,  7.,  0.]])

First here we are using rand() to have random items in the corresponding dimensions  and store it in tensor . Then creating a new tensor by by function new_tensor() making gradiend_descent value as false. And we are multiplying it with tensor such that current tensor z will take dimension in tensor. We can check the length of tensor z with .shape method. And can also permute some indices with .permute.

In [0]:
# Example 2 - working
z.abs_()
z.add_(2,alpha=1)

tensor([[11.,  2.,  9.],
        [ 7.,  9.,  2.]])

Here we are using abs_() function to convert all the tensor value positive , then here we are using .add_ to add input number to each item of tensor with alpha value to be 1.

In [0]:

# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.tensor([[1, 2,-1.], [3, 4, 5]])
tensor2 = torch.exp(tensor).sum()
w = torch.rand(2,3)
w.allclose(tensor, rtol=1e-05, atol=1e-08, equal_nan=False)
w.argsort()
w.asin_()


tensor([[0.4196, 0.4808, 0.9494],
        [0.0830, 0.3258, 0.5885]])

In allclose function all of this represents:
input (Tensor) – first tensor to compare

other (Tensor) – second tensor to compare

atol (float, optional) – absolute tolerance. Default: 1e-08

rtol (float, optional) – relative tolerance. Default: 1e-05

equal_nan (bool, optional) – if True, then two NaN s will be considered equal. Default: False

argsort function is used to output all the elements in tensors in sorted order.
And converting the output to asin_ will  provides support for the inverse sine function in PyTorch. It expects the input to be in the range [-1, 1] and gives the output in radian form. It returns nan if the input does not lie in the range [-1, 1]. The input type is tensor and if the input contains more than one element, element-wise inverse sine is computed.

Closing comments about when to use this function

## Function 2 - 1.torch.as_strided , 2.torch.bincount, 3 . torch.diag_embed
1. In torch.as_strided function it will Create a view of an existing torch.Tensor input with specified size, stride and storage_offset.
2. In bincount function each tensor value have some weight associated with it such that input will contain the range of tensor and weigt means how far te tensor will be that's why last element is the dimension associated with weights as a tensor input.
3. In diag_embed in the tensor the inputs will be added along the diagonal only.


In [0]:
# Example 1 - working
w.as_strided((3,1),(2,2), storage_offset=0)
t = torch.tensor([[9,0,0],[-9,-1.,-4],[0,-9,-8]])
#w.baddbmm_(t,t, beta=1, alpha=1) 
w.bernoulli_(p=0.5, generator=None) 

tensor([[1., 1., 1.],
        [0., 1., 0.]])

Here bernoulli_() function will Fills each location of self with an independent sample from Bernoulli(p) . self can have integral dtype.

In [0]:
# Example 2 - working
torch.bincount(weights=torch.tensor([2]),input=torch.tensor([11]) ,minlength=1)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.], dtype=torch.float64)

Here the function bincount() take two tensors one would be the input which is a tensor tells the range of input values and weights which tells how much max value of the tensor and minlength tells that only 1-d tensor input is to be taken.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
#torch.cholesky_solve(input=torch.tensor([[5,6],[8,9]]),input2=torch.tensor([[3,8],[1,8]]),upper=False)
torch.diag_embed(t,offset=0, dim1=-2, dim2=-1)

tensor([[[ 9.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[-9.,  0.,  0.],
         [ 0., -1.,  0.],
         [ 0.,  0., -4.]],

        [[ 0.,  0.,  0.],
         [ 0., -9.,  0.],
         [ 0.,  0., -8.]]])

Makes a tensor whose diagonals of certain 2D planes (determined by dim1 and dim2) are filled by input. To encourage making bunched corner to corner frameworks, the 2D planes shaped by the last two components of the returned tensor are picked as a matter of course. 

The contention offset controls which diagonal to consider: 

Whenever offset = 0, it is the principle diagonal. 

Whenever offset > 0, it is over the principle diagonal. 

Whenever offset < 0, it is beneath the principle corner to corner. 

The size of the new grid will be determined to make the predetermined diagonal of the size of the last information measurement. Note that for balance other than 00 , the request for dim1 and dim2 matters. Trading them is identical to changing the indication of offset.

Closing comments about when to use this function

## Function 3 - 1. torch.erfinv, 2. torch.spilt() 3. torch.sparse_mask

erfinv will deal with inverse error function of input element.
As the name suggest .split function will split the function into chunks and then apply its functionality on them.
sparse_mask take input value and convert it along with the mask input into list.


In [0]:
# Example 1 - working
torch.erfinv(t) 

tensor([[nan, 0., 0.],
        [nan, -inf, nan],
        [0., nan, nan]])

torch.erfinv(input, out=None) → Tensor
Computes the inverse error function of each element of input. The inverse error function is defined in the range (-1, 1)(−1,1) 



In [0]:
# Example 2 - working
#torch.index_fill(t,w,2,dim=1) 
#torch.scatter_add(dim=1, index=t, src=w) 
torch.split(t,split_size_or_sections=2,dim=0)

(tensor([[ 9.,  0.,  0.],
         [-9., -1., -4.]]), tensor([[ 0., -9., -8.]]))

Parts the tensor into chunks. Each chunks is a perspective on the first tensor. 

On the off chance that split_size_or_sections is a whole number sort, at that point tensor will be part into similarly measured pieces (if conceivable). Last piece will be smaller  if the tensor size along the given measurement dimensions isn't distinguishable by split_size. 

On the other hand that split_size_or_sections is a rundown, at that point tensor will be part into len(split_size_or_sections) chunks with sizes in dimensions as indicated by split_size_or_sections

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
nnz = 5
dims = [5, 5,2,2]
I = torch.cat([torch.randint(0, dims[0], size=(nnz,)),
                   torch.randint(0, dims[1], size=(nnz,))], 0).reshape(2, nnz)
V = torch.randn(nnz, dims[2], dims[3])
size = torch.Size(dims)
S = torch.sparse_coo_tensor(I,V,size).coalesce()
D = torch.randn(dims)
D.sparse_mask(S)

tensor(indices=tensor([[0, 2, 3, 4, 4],
                       [1, 4, 3, 0, 4]]),
       values=tensor([[[-0.8894,  0.4687],
                       [ 0.2962,  0.2355]],

                      [[ 0.7393,  0.1254],
                       [-0.6831,  1.1992]],

                      [[-1.3271,  0.6146],
                       [ 1.5161,  0.5639]],

                      [[-0.2580, -0.2889],
                       [-0.0432,  1.5647]],

                      [[ 1.4115,  2.6030],
                       [ 0.2458,  0.0589]]]),
       size=(5, 5, 2, 2), nnz=5, layout=torch.sparse_coo)

Returns another SparseTensor with values from Tensor info iltered by indices of mask and values are ignored. input and mask must have the same shape. 

Parameters 

input (Tensor) – an info Tensor 

cover (SparseTensor) – a SparseTensor which we channel input dependent on its lists

Closing comments about when to use this function

## Function 4 - 

1. storage_offset() : It deals with the subtensors.
2. stride : It deals with the dimensions present as agruments.
3. sum : It will sum up the elements in the matrix.

In [0]:
# Example 1 - working
#torch.stft(n_fft=t,hop_length=None, win_length=None, window=None, center=True, pad_mode='reflect', normalized=False, onesided=True)
t.storage_offset()

0

Since here there is no self argument calling in function so the offset for tensor t will be 0.

In [0]:
# Example 2 - working
t.stride()

(3, 1)

stride is when one value jumps to the other . It mainly takes dimensions as argument in tensor form such that for each value we returned the dimension of tensor and return nothing if no argument is passed .

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.sum(t,dtype=None)

tensor(-22.)

Here sum function is adding all the tensors elements and giving us the out since in tensor all the element in matrix converted into float so it will ignore the different dtype elementsonly the total no. of elements in dimenional array should be same.

Closing comments about when to use this function

## Function 5 - Here we are using functions taking eigen value and eigenvectors

Basically here the concept of upper triangular matrix is applied on the vector.

In [0]:
# Example 1 - working
torch.symeig(t,eigenvectors=False, upper=True)

torch.return_types.symeig(eigenvalues=tensor([-9.8151,  0.8151,  9.0000]), eigenvectors=tensor([]))

This function will take the concept of upper triangular matrix such that it will be used to calculate the eigen values and eigen vectors . This capacityreturns eigenvalues and eigenvectors of a genuine symmetric grid input or a cluster of genuine symmetric networks, spoke to by a namedtuple (eigenvalues, eigenvectors). 

This capacity ascertains all eigenvalues (and vectors) of info to such an extent that \text{input} = V \text{diag}(e) V^Tinput=Vdiag(e)V 


The boolean contention eigenvectors characterizes calculation of both eigenvectors and eigenvalues or eigenvalues as it were. 

On the off chance that it is False, just eigenvalues are figured. On the off chance that it is True, the two eigenvalues and eigenvectors are figured. 

Since the information network input should be symmetric, just the upper triangular segment is utilized naturally. 

In the event that upper is False, at that point lower triangular segment is utilized.

In [0]:
# Example 2 - working
torch.symeig(t, eigenvectors=True)

torch.return_types.symeig(eigenvalues=tensor([-9.8151,  0.8151,  9.0000]), eigenvectors=tensor([[ 0.0000,  0.0000,  1.0000],
        [ 0.4132, -0.9106,  0.0000],
        [ 0.9106,  0.4132,  0.0000]]))

It will be same as eigen values but now since eigenvectors = True it will print both eigenvalues and eigenvectors.

In [0]:
# Example 3 - breaking (to illustrate when it breaks
torch.rand(2)


tensor([0.0184, 0.8770])

two rows random values print

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next
Functions of torch.tensors and torch will be used.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 2.4MB/s 


In [0]:
import jovian

In [0]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
